apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nats-secret-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: auth.conf
    remoteRef:
      key: nats
      property: auth_conf
