apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nats-secret-config
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: auth.conf
    remoteRef:
      key: kv/services/nats/auth-conf
      property: auth_conf_json
