apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: w7x6t-app-of-apps
spec:
  project: w7x6t
  source:
    repoURL: https://scm.w7x6t.dev/w7x6t/root-app-of-apps.git
    path: ./by-cluster/red-squadron/app-of-apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
