apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
- name: cilium
  includeCRDs: true
  repo: https://helm.cilium.io/
  releaseName: cilium
  namespace: kube-system
  version: "1.19.4"
  valuesInline:
    rollOutCiliumPods: true
    ipam:
      mode: kubernetes
    kubeProxyReplacement: true
    securityContext:
      capabilities:
        ciliumAgent: [CHOWN, KILL, NET_ADMIN, NET_RAW, IPC_LOCK, SYS_ADMIN, SYS_RESOURCE, DAC_OVERRIDE, FOWNER, SETGID, SETUID]
        cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    operator:
      replicas: 1
    # Native routing and L2 Announce incompatible, affects all config down to and including loadbalancer:
    # https://github.com/cilium/cilium/issues/27800
    routingMode: tunnel
    tunnelProtocol: geneve
    loadbalancer:
      mode: dsr
      dsrDispatch: geneve
    bpf:
      masquerade: true
    k8s:
      requireIpv4PodCIDR: true
    localRedirectPolicy: true
    bgpControlPlane:
      enabled: false
    l2announcements:
      enabled: true
      leaseDuration: 15s
      leaseRenewDeadline: 5s
      leaseRetryPeriod: 2s
    l7proxy: false
    envoy:
      enabled: false
    gatewayAPI:
      enabled: false
    k8sClientRateLimit:
      qps: 1200
      burst: 1800
    k8sServiceHost: localhost
    k8sServicePort: 7445
resources:
- resources/l2-lb-ip-pool.yaml
- resources/l2-policy.yaml
