apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v3.4.3
# - ./resources/ingress.yaml
- ./resources/routes.yaml
- ./resources/oidc-credentials.yaml
# Repository Credentials
- ./resources/repository-credentials/codeberg-wtaylor-credentials.yaml
- ./resources/repository-credentials/w7x6t-dev-credentials.yaml
- ./resources/repository-credentials/wtaylor-github-credentials.yaml
# Repositories
- ./resources/repositories/codeberg-wtaylor-repositories.yaml
- ./resources/repositories/w7x6t-dev-repositories.yaml
- ./resources/repositories/github-wtaylor-repositories.yaml
patches:
- path: ./patches/argocd-cmd-params-cm.yaml
- path: ./patches/argocd-cm.yaml
- path: ./patches/argocd-rbac-cm.yaml
