default_provider = "onepass"

[providers.onepass]
type = "1password"
vault = "Homelab"

[secrets]
SECRETS_K8S_SINGLE_SPICY_ESO_OP_SA = { provider = "onepass", value = "1password-sa-eso-single-spicy/credential" }
