[tools]
argocd = "2.13.3"
"github:coreos/butane" = "0.25.1"
jq = "1.8.1"
opentofu = "1.11.1"
python = { version = "3.13.1", virtualenv = ".venv" }
terraform = "1.11.4"
terragrunt = "0.96.1"
usage = "3.4.0"
uv = "0.5.11"
vault = "1.18.3"
velero = "1.14.0"
yq = "4.53.3"
helm = "3.19.4"
kustomize = "5.8.1"

[settings]
experimental = true

[settings.python]
uv_venv_auto = true

[env]
_.python.venv = { path = ".venv", create = true }
VAULT_ADDR = "https://vault.tk831.net"
ANSIBLE_PIPELINING = "True"

[tasks."ansible:playbook"]
run = 'ansible-playbook -i ansible/common/inventory/ ansible/machines/{{arg(name="machine_playbook")}}'
