[tools]
argocd = "2.13.3"
"github:coreos/butane" = "0.25.1"
jq = "1.8.1"
opentofu = "1.12.6"
python = { version = "3.13.1" }
terraform = "1.11.4"
terragrunt = "0.96.1"
uv = "0.5.11"
velero = "1.14.0"
yq = "4.53.3"
helm = "3.19.4"
kustomize = "5.8.1"
bun = "1.2.17"
fnox = "1.34.0"
envsubst = "1.4.3"
hk = "1.54.0"

[settings]
experimental = true

[settings.python]
uv_venv_auto = "create|source"

[env]
ANSIBLE_PIPELINING = "True"
