apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vector-nats-home-wiretap-nats-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: NATS_USERNAME
    remoteRef:
      key: kv/services/vector-nats-home-wiretap/nats-credentials
      property: username
  - secretKey: NATS_PASSWORD
    remoteRef:
      key: kv/services/vector-nats-home-wiretap/nats-credentials
      property: password
