apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vector-nats-home-wiretap-nats-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: NATS_USERNAME
    remoteRef:
      key: vector-nats-home-wiretap
      property: nats_username
  - secretKey: NATS_PASSWORD
    remoteRef:
      key: vector-nats-home-wiretap
      property: nats_password
