- name: Ensure victoria-logs directories exist
  become: true
  loop:
  - /var/mnt/victorialogs/data
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: victoria-logs
    group: victoria-logs
    mode: '0750'
- name: Create Victoria Logs quadlet
  become: true
  containers.podman.podman_container:
    name: victoria-logs
    state: quadlet
    image: docker.io/victoriametrics/victoria-logs:v1.43.1
    uidmap: ["0:2002"]
    command:
    - -storageDataPath=/mnt/data
    - -retention.maxDiskSpaceUsageBytes=100GiB
    volume:
    - /var/mnt/victorialogs/data:/mnt/data:Z
    network:
    - podman
    - observability-stack.network
    ports:
    - "9428:9428"
    quadlet_options:
    - |
      [Unit]
      RequiresMountsFor=/var/mnt/victorialogs/data

      [Service]
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=default.target
  register: container_definition
- name: Create Loki Victoria Logs Proxy
  become: true
  containers.podman.podman_container:
    name: loki-vl-proxy
    state: quadlet
    image: ghcr.io/reliablyobserve/loki-vl-proxy:1.23.0
    command:
    - "-backend=http://victoria-logs:9428"
    network:
    - podman
    - observability-stack.network
    ports:
    - "3100:3100"
    quadlet_options:
    - |
      [Unit]
      RequiresMountsFor=/var/mnt/victorialogs/data

      [Service]
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=default.target
  register: proxy_container_definition
- name: systemd daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
- name: (Re)start victoria-logs service
  become: true
  ansible.builtin.systemd:
    name: victoria-logs
    enabled: true
    state: "{{ 'restarted' if container_definition.changed else 'started' }}"
- name: (Re)start loki-vl-proxy service
  become: true
  ansible.builtin.systemd:
    name: loki-vl-proxy
    enabled: true
    state: "{{ 'restarted' if proxy_container_definition.changed else 'started' }}"
