apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-csi-plugin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: api_token_id
    remoteRef:
      key: single-spicy-proxmox-credentials
      property: api_token_id
  - secretKey: api_token
    remoteRef:
      key: single-spicy-proxmox-credentials
      property: api_token
  target:
    template:
      engineVersion: v2
      data:
        config.yaml: |
          clusters:
          - url: https://tardis.willtaylor.info:8006/api2/json
            insecure: true
            token_id: "{{ .api_token_id }}"
            token_secret: "{{ .api_token }}"
            region: tardis
