apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: github-wtaylor-repositories
stringData:
  type: git
  url: https://github.com/wtaylor/*
