apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: w7x6t-dev-repositories
stringData:
  type: git
  url: https://scm.w7x6t.dev/*
