apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: codeberg-wtaylor-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: username
    remoteRef:
      key: argocd/repo-creds-codeberg-wtaylor/username
  - secretKey: password
    remoteRef:
      key: argocd/repo-creds-codeberg-wtaylor/password
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: git
        url: https://codeberg.org/wtaylor
        username: '{{ .username }}'
        password: '{{ .password }}'
