apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: w7x6t-dev-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: username
    remoteRef:
      key: argocd
      property: repo_creds_w7x6t_dev_username
  - secretKey: password
    remoteRef:
      key: argocd
      property: repo_creds_w7x6t_dev_password
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: git
        url: https://scm.w7x6t.dev/
        username: '{{ .username }}'
        password: '{{ .password }}'
