apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app.kubernetes.io/name: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homeassistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homeassistant
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: homeassistant-data
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant:2025.8.3
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Europe/London
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /config
