apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: vector
  repo: https://helm.vector.dev
  releaseName: vector-agent
  namespace: vector
  version: "0.50.0"
  valuesInline:
    role: Agent
    podAnnotations:
      vector.dev/exclude: "true"
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
      limits:
        memory: 2048Mi
generators:
- generators/vector-yaml-config-map.yaml
