- name: Ensure openbao directory exists
  become: true
  loop:
  - /var/mnt/vault/openbao
  - /var/mnt/vault/openbao/config
  - /var/mnt/vault/openbao/data
  - /var/mnt/vault/openbao/logs
  - /var/mnt/vault/medusa/config
  - /var/mnt/vault/medusa/export
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: openbao
    group: openbao
    mode: '0700'
- name: Copy vault configuration
  become: true
  ansible.builtin.template:
    src: openbao.hcl.j2
    dest: /var/mnt/vault/openbao/config/openbao.hcl
    owner: openbao
    group: openbao
    mode: '0640'
  register: config
- name: Create openbao quadlet
  become: true
  containers.podman.podman_container:
    name: openbao
    state: quadlet
    image: ghcr.io/openbao/openbao:2.5.0
    uidmap: ["0:2000"]
    gidmap: ["0:2000"]
    command: ["bao", "server", "-config=/openbao/config/openbao.hcl"]
    env:
      SKIP_CHOWN: "true"
      BAO_SKIP_DROP_ROOT: "true"
    network: [podman, "{{ proxy_network }}.network"]
    volume:
    - /var/mnt/vault/openbao/config:/openbao/config:z
    - /var/mnt/vault/openbao/data:/openbao/file:z
    - /var/mnt/vault/openbao/logs:/openbao/logs:z
    ports:
    - "8200:8200"
    quadlet_options:
    - |
      [Unit]
      RequiresMountsFor=/var/mnt/vault

      [Service]
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=default.target
  register: container_definition
- name: (Re)start openbao server service
  become: true
  ansible.builtin.systemd:
    name: openbao
    enabled: true
    daemon_reload: true
    state: "{{ 'restarted' if container_definition.changed else 'started' }}"
- name: Create medusa token secret
  become: true
  containers.podman.podman_secret:
    state: present
    name: medusa_vault_token
    data: "{{ lookup('ansible.builtin.file', '/run/media/wtaylor/ROOTS/secrets/medusa_token') }}"
- name: Create medusa-export public key
  become: true
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.file', '/run/media/wtaylor/ROOTS/secrets/medusa_public_key') }}"
    dest: /var/mnt/vault/medusa/config/public.key
    owner: openbao
    group: openbao
    mode: '0640'
- name: Create medusa-export quadlet
  become: true
  containers.podman.podman_container:
    name: medusa-export
    state: quadlet
    image: ghcr.io/jonasvinther/medusa@sha256:bc4696d3328bed5a0712318d643766e36c87d2ae836d14170d010df6abf0447d # 0.7.3
    user: "0:0"
    uidmap: ["0:2000"]
    gidmap: ["0:974"]
    secrets:
    - medusa_vault_token,type=env,target=VAULT_TOKEN
    env:
      VAULT_ADDR: https://vault.tk831.net
    volume:
    - /var/mnt/vault/medusa/config:/mnt/config:z
    - /var/mnt/vault/medusa/export:/mnt/export:z
    command: [export, kv, -e, -p, /mnt/config/public.key, -o, /mnt/export/openbao-server]
    quadlet_options:
    - |
      [Unit]
      RequiresMountsFor=/var/mnt/vault

      [Service]
      Type=oneshot
  register: container_definition
- name: Create medusa-export timer unit
  become: true
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=medusa-export timer

      [Timer]
      OnCalendar=*-*-* 01:00:00
      Persistent=true
      Unit=medusa-export.service

      [Install]
      WantedBy=default.target
    dest: /etc/systemd/system/medusa-export.timer
    owner: root
    group: root
    mode: '0644'
- name: Enable timer
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: medusa-export.timer
    state: started
    enabled: true
