apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: apiToken
    remoteRef:
      key: cert-manager
      property: cloudflare_api_token
