- hosts: container-services.lan.tk831.net
  remote_user: wtaylor
  vars:
    proxy_network: proxy
  roles:
  - role: ../../../common/roles/create-system-users
    system_users:
    - username: caddy
      uid: 2000
    - username: versitygw
      uid: 2005
  - role: ../../../common/roles/prepare-disks
    disks:
    - serial: viscsi-caddy-data
      label: caddy-data
      mountpoint: /var/mnt/caddy/data
      owner: caddy
      mode: "0750"
    - serial: viscsi-vs3-data
      label: versitygw-data
      fstype: xfs
      mountpoint: /var/mnt/versitygw/data
      owner: versitygw
      mode: "0750"
  - role: ../../../common/roles/quadlet-network
    network_name: "{{ proxy_network }}"
  - role: ./roles/quadlet-versitygw
  - role: ../../../common/roles/quadlet-caddy
    caddy_data_dir: "/var/mnt/caddy/data"
    cloudflare_token: "{{(lookup('community.general.onepassword', 'nas-rp-server', vault='Homelab', field='cloudflare_credentials'))}}"
    requires_mounts_for: /var/mnt/caddy/data
    proxy_hosts:
    - domain: s3.tk831.net
      dest: http://versitygw:8080
    - domain: ui.s3.tk831.net
      dest: http://versitygw:8081
    - domain: databasus.tk831.net
      dest: http://data-backup-server.lan.tk831.net:8081
  - role: ../../../common/roles/restic-backup
    repository:
      url: rest:http://data-backup-server.lan.tk831.net:8080/hosts/container-services/quadlets/versitygw
      password: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_repopassword'))}}"
      rest_username: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_username'))}}"
      rest_password: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_password'))}}"
    retention:
      daily: 7
      weekly: 4
      monthly: 3
      yearly: 2
    systemd:
      on_calendar: "*-*-* 02:00:00"
      unit_suffix: versitygw
    backup_now: false
    directories:
    - /var/mnt/versitygw/data
  - role: ../../../common/roles/restic-backup
    repository:
      url: rest:http://data-backup-server.lan.tk831.net:8080/hosts/container-services/quadlets/caddy
      password: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_repopassword'))}}"
      rest_username: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_username'))}}"
      rest_password: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_password'))}}"
    retention:
      daily: 7
      weekly: 4
      monthly: 3
      yearly: 2
    systemd:
      on_calendar: "*-*-* 02:00:00"
      unit_suffix: caddy
    backup_now: false
    directories:
    - /var/mnt/caddy/data
