- hosts: container-services.willtaylor.info
  remote_user: wtaylor
  vars:
    proxy_network: proxy
  roles:
  - role: ../../../common/roles/create-system-users
    system_users:
    - username: caddy
      uid: 2000
    - username: vector
      uid: 2001
    - username: victoria-logs
      uid: 2002
    - username: victoria-metrics
      uid: 2003
    - username: grafana
      uid: 2004
    - username: versitygw
      uid: 2005
  - role: ../../../common/roles/prepare-disks
    disks:
    - serial: viscsi-caddy-data
      label: caddy-data
      mountpoint: /var/mnt/caddy/data
      owner: caddy
      mode: "0750"
    - serial: viscsi-vl-data
      label: victoria-logs-data
      mountpoint: /var/mnt/victorialogs/data
      owner: victoria-logs
      mode: "0750"
    - serial: viscsi-vm-data
      label: victoria-metrics-data
      mountpoint: /var/mnt/victoriametrics/data
      owner: victoria-metrics
      mode: "0750"
    - serial: viscsi-grafana-data
      label: grafana-data
      mountpoint: /var/mnt/grafana/data
      owner: grafana
      mode: "0750"
    - serial: viscsi-vector-data
      label: vector-data
      mountpoint: /var/mnt/vector/data
      owner: vector
      mode: "0750"
    - serial: viscsi-vs3-data
      label: versitygw-data
      fstype: xfs
      mountpoint: /var/mnt/versitygw/data
      owner: versitygw
      mode: "0750"
  - role: ../../../common/roles/quadlet-network
    network_name: "{{ proxy_network }}"
  - role: ./roles/quadlet-versitygw
  - role: ../../../common/roles/quadlet-network
    network_name: observability-stack
  - role: ./roles/quadlet-victoria-logs
  - role: ./roles/quadlet-victoria-metrics
  - role: ./roles/quadlet-vector-aggregator
  - role: ./roles/quadlet-grafana
  - role: ../../../common/roles/quadlet-caddy
    caddy_data_dir: "/var/mnt/caddy/data"
    cloudflare_token: "{{(lookup('community.general.onepassword', 'nas-rp-server', vault='Homelab', field='cloudflare_credentials'))}}"
    requires_mounts_for: /var/mnt/caddy/data
    proxy_hosts:
    - domain: s3.tk831.net
      dest: http://versitygw:8080
    - domain: ui.s3.tk831.net
      dest: http://versitygw:8081
    - domain: grafana.tk831.net
      dest: http://grafana:3000
    - domain: databasus.tk831.net
      dest: http://data-backup-server.willtaylor.info:8081
  - role: ./roles/quadlet-pve-exporter
  - role: ../../../common/roles/restic-backup
    repository:
      url: rest:http://data-backup-server.willtaylor.info:8080/hosts/container-services/quadlets/versitygw
      password: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_repopassword'))}}"
      rest_username: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_username'))}}"
      rest_password: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_password'))}}"
    retention:
      daily: 7
      weekly: 4
      monthly: 3
      yearly: 2
    systemd:
      on_calendar: "*-*-* 02:00:00"
      unit_suffix: versitygw
    backup_now: false
    directories:
    - /var/mnt/versitygw/data
  - role: ../../../common/roles/restic-backup
    repository:
      url: rest:http://data-backup-server.willtaylor.info:8080/hosts/container-services/quadlets/grafana
      password: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_repopassword'))}}"
      rest_username: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_username'))}}"
      rest_password: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_password'))}}"
    retention:
      daily: 7
      weekly: 4
      monthly: 3
      yearly: 2
    systemd:
      on_calendar: "*-*-* 02:00:00"
      unit_suffix: grafana
    backup_now: false
    directories:
    - /var/mnt/grafana/data
  - role: ../../../common/roles/restic-backup
    repository:
      url: rest:http://data-backup-server.willtaylor.info:8080/hosts/container-services/quadlets/victoria-logs
      password: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_repopassword'))}}"
      rest_username: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_username'))}}"
      rest_password: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_password'))}}"
    retention:
      daily: 7
      weekly: 2
      monthly: 1
      yearly: 0
    systemd:
      on_calendar: "*-*-* 02:00:00"
      unit_suffix: victoria-logs
    backup_now: false
    directories:
    - /var/mnt/victorialogs/data
  - role: ../../../common/roles/restic-backup
    repository:
      url: rest:http://data-backup-server.willtaylor.info:8080/hosts/container-services/quadlets/victoria-metrics
      password: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_repopassword'))}}"
      rest_username: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_username'))}}"
      rest_password: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_password'))}}"
    retention:
      daily: 7
      weekly: 2
      monthly: 1
      yearly: 0
    systemd:
      on_calendar: "*-*-* 02:00:00"
      unit_suffix: victoria-metrics
    backup_now: true
    directories:
    - /var/mnt/victoriametrics/data
  - role: ../../../common/roles/restic-backup
    repository:
      url: rest:http://data-backup-server.willtaylor.info:8080/hosts/container-services/quadlets/caddy
      password: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_repopassword'))}}"
      rest_username: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_username'))}}"
      rest_password: "{{(lookup('community.general.onepassword', 'data-backup-server', vault='Homelab', field='restic_credentials_password'))}}"
    retention:
      daily: 7
      weekly: 4
      monthly: 3
      yearly: 2
    systemd:
      on_calendar: "*-*-* 02:00:00"
      unit_suffix: caddy
    backup_now: false
    directories:
    - /var/mnt/caddy/data
  - role: ../../../common/roles/vector-agent
    vector_config:
      data_dir: /opt/vector/data
      api:
        enabled: true
      schema:
        log_namespace: true
      sources:
        vector_logs:
          type: internal_logs
        journald:
          type: journald
        host_metrics:
          type: host_metrics
          scrape_interval_secs: 60
          filesystem:
            devices:
              excludes: [binfmt_misc]
            filesystems:
              includes:
              - ext*
              - xfs
              - ntfs
              - btrfs
              - zfs
              - vfat
              - fat32
            mountPoints:
              excludes:
              - "*/proc/sys/fs/binfmt_misc"
              - "/var/lib/containers/**"
        vector_internal_metrics:
          type: internal_metrics
          scrape_interval_secs: 60
      transforms:
        mapped_journal_logs:
          type: remap
          inputs: [journald]
          source: |-
            .message = .
            .timestamp = %journald.timestamp
            .host = %journald.host
            .service = %journald.metadata._SYSTEMD_UNIT
      sinks:
        console:
          type: console
          inputs: ["vector_logs"]
          encoding:
            codec: text
        vector_server:
          type: vector
          inputs: [host_metrics, mapped_journal_logs, vector_internal_metrics]
          address: http://vector.tk831.net:6001
          version: "2"
          tls:
            enabled: false
