- name: Ensure Vector directories exist
  become: true
  loop:
  - /var/mnt/vector/data
  - /var/mnt/vector/data/config
  - /var/mnt/vector/data/data
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: vector
    group: vector
    mode: '0750'
- name: Copy vector configuration
  become: true
  ansible.builtin.copy:
    src: vector.yaml
    dest: /var/mnt/vector/data/config/vector.yaml
    owner: vector
    group: vector
    mode: '0640'
  register: config
- name: Create Vector Aggregator quadlet
  become: true
  containers.podman.podman_container:
    name: vector-aggregator
    state: quadlet
    image: docker.io/timberio/vector:0.52.0-debian
    uidmap: ["0:2001"]
    volume:
    - /var/mnt/vector/data/data:/mnt/data:z
    - /var/mnt/vector/data/config:/etc/vector:ro,z
    network:
    - podman
    - observability-stack.network
    ports:
    - "8687:8687"
    - "6000:6000"
    - "6001:6001"
    - "6002:6002"
    - "9090:9090"
    - "6050:6050"
    - "6051:6051"
    quadlet_options:
    - |
      [Unit]
      RequiresMountsFor=/var/mnt/vector/data

      [Service]
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=default.target
  register: container_definition
- name: (Re)start vector-aggregator service
  become: true
  ansible.builtin.systemd:
    name: vector-aggregator
    daemon_reload: true
    enabled: true
    state: "{{ 'restarted' if (container_definition.changed or config.changed) else 'started' }}"
