apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nodered-oauth-client-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: client_id
    remoteRef:
      key: nodered
      property: oauth_client_credentials_client_id
  - secretKey: client_secret
    remoteRef:
      key: nodered
      property: oauth_client_credentials_client_secret
