apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: joplin-db-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  target:
    deletionPolicy: Delete
  data:
  - secretKey: username
    remoteRef:
      key: joplin/postgres/username
  - secretKey: password
    remoteRef:
      key: joplin/postgres/password
