apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: joplin-db-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  target:
    deletionPolicy: Delete
  data:
  - secretKey: username
    remoteRef:
      key: kv/services/joplin/postgres-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: kv/services/joplin/postgres-credentials
      property: password
