apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: joplin-s3-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: access_key
    remoteRef:
      key: joplin/s3/access_key
  - secretKey: secret_key
    remoteRef:
      key: joplin/s3/secret_key
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        storageDriver: "Type=S3; Region=us-east-1; AccessKeyId={{ .access_key }}; SecretAccessKeyId={{ .secret_key }}; Bucket=joplin; Endpoint=https://s3.tk831.net"
