apiVersion: v1
kind: Service
metadata:
  name: joplin
  labels:
    app.kubernetes.io/name: joplin
spec:
  selector:
    app.kubernetes.io/name: joplin
  ports:
  - name: http
    port: 80
    targetPort: 22300
  type: ClusterIP
