apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-database-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: username
    remoteRef:
      key: immich/postgres-credentials/username
  - secretKey: password
    remoteRef:
      key: immich/postgres-credentials/password
  target:
    deletionPolicy: Delete
    template:
      data:
        db_url: "postgresql://{{.username}}:{{.password}}@postgres-tk831-immich-rw:5432/immich"
