apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-tk831-immich-role-immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: username
    remoteRef:
      key: immich/postgres/username
  - secretKey: password
    remoteRef:
      key: immich/postgres/password
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: '{{ .username }}'
        password: '{{ .password }}'
