apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
spec:
  resources:
    requests:
      storage: 400Gi
  volumeMode: Filesystem
  storageClassName: proxmox-zfs
  volumeName: pvc-a6c29bba-25b7-4f83-b5e3-e2612fc15102
  accessModes:
  - ReadWriteOnce
