- hosts: [red-one]
  remote_user: root
  handlers:
  - import_tasks: ../../../common/handlers/global.yaml
  roles:
  - role: ../../../common/roles/proxmox-configure-nonprod-sources
  - role: ../../../common/roles/proxmox-disable-subscription-nag
  - role: ../../../common/roles/update-system
  - role: ../../../common/roles/create-user
    username: "{{(lookup('community.general.onepassword', 'pve-wtaylor-user', vault='Homelab', field='username'))}}"
    password: "{{(lookup('community.general.onepassword', 'pve-wtaylor-user', vault='Homelab', field='password'))}}"
    salt: "{{(lookup('community.general.onepassword', 'pve-wtaylor-user', vault='Homelab', section='security', field='pam_salt'))}}"
  - role: ./roles/proxmox-enable-vfio
  - role: ../../../common/roles/proxmox-notifications
    mailer_name: admin-mail
    matcher_name: admin-matcher
    author: Proxmox VE - Red Squadron
    from_address: proxmox-red-squadron@w7x6t.dev
    mailto_users: [wtaylor@pam]
    mode: tls
    smtp_server: smtp.tem.scaleway.com
    smtp_port: 465
    smtp_username: "{{(lookup('community.general.onepassword', 'scaleway-proxmox', vault='Homelab', field='smtp_username'))}}"
    smtp_password: "{{(lookup('community.general.onepassword', 'scaleway-proxmox', vault='Homelab', field='password'))}}"
  - role: ../../../common/roles/vector-agent
    install: true
    agent_user:
      groups: [systemd-journal]
    vector_config:
      data_dir: /opt/vector/data
      api:
        enabled: true
      schema:
        log_namespace: true
      sources:
        vector_logs:
          type: internal_logs
        journald:
          type: journald
        host_metrics:
          type: host_metrics
          scrape_interval_secs: 60
          filesystem:
            devices:
              excludes: [binfmt_misc]
            filesystems:
              includes:
              - ext*
              - xfs
              - ntfs
              - btrfs
              - zfs
              - vfat
              - fat32
            mountPoints:
              excludes:
              - "*/proc/sys/fs/binfmt_misc"
              - "/var/lib/containers/**"
        vector_internal_metrics:
          type: internal_metrics
          scrape_interval_secs: 60
      transforms:
        mapped_journal_logs:
          type: remap
          inputs: [journald]
          source: |-
            .message = .
            .timestamp = %journald.timestamp
            .host = %journald.host
            .service = %journald.metadata._SYSTEMD_UNIT
      sinks:
        console:
          type: console
          inputs: ["vector_logs"]
          encoding:
            codec: text
        vector_server:
          type: vector
          inputs: [host_metrics, mapped_journal_logs, vector_internal_metrics]
          address: http://vector.tk831.net:6001
          version: "2"
          tls:
            enabled: false
