apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-default-admin-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: username
    remoteRef:
      key: postgres
      property: dbc_postgres_default_credentials_superuser_username
  - secretKey: password
    remoteRef:
      key: postgres
      property: dbc_postgres_default_credentials_superuser_password
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: '{{ .username }}'
        password: '{{ .password }}'
