apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-tk831-default
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.1
  instances: 1
  primaryUpdateStrategy: unsupervised
  superuserSecret:
    name: postgres-default-admin-credentials
  enableSuperuserAccess: true
  storage:
    storageClass: proxmox-zfs
    size: 20Gi
    resizeInUseVolumes: false
  walStorage:
    storageClass: proxmox-zfs
    size: 2Gi
    resizeInUseVolumes: false
  postgresql:
    parameters:
      max_slot_wal_keep_size: "1GB"
  managed:
    roles:
    - name: gitea
      ensure: present
      comment: Gitea app user
      superuser: false
      login: true
      passwordSecret:
        name: postgres-tk831-default-role-gitea
    - name: keycloak
      ensure: present
      comment: Keycloak app user
      superuser: false
      login: true
      passwordSecret:
        name: postgres-tk831-default-role-keycloak
    - name: nextcloud
      ensure: present
      comment: Nextcloud app user
      superuser: false
      login: true
      passwordSecret:
        name: postgres-tk831-default-role-nextcloud
    - name: paperless
      ensure: present
      comment: Paperless app user
      superuser: false
      login: true
      passwordSecret:
        name: postgres-tk831-default-role-paperless
    - name: joplin
      ensure: present
      comment: Joplin app user
      superuser: false
      login: true
      passwordSecret:
        name: postgres-tk831-default-role-joplin
    - name: linkwarden
      ensure: present
      comment: Linkwarden app user
      superuser: false
      login: true
      passwordSecret:
        name: postgres-tk831-default-role-linkwarden
    - name: sparkyfitness_admin
      ensure: present
      comment: SparkyFitness admin user
      superuser: false
      login: true
      passwordSecret:
        name: postgres-tk831-default-role-sparkyfitness-admin
    - name: sparkyfitness_app
      ensure: present
      comment: SparkyFitness app user
      superuser: false
      login: true
      passwordSecret:
        name: postgres-tk831-default-role-sparkyfitness-app
    services:
      additional:
      - selectorType: rw
        serviceTemplate:
          metadata:
            name: "postgres-default-lan-rw"
          spec:
            type: LoadBalancer
            loadBalancerIP: 172.28.3.136
  resources:
    requests:
      memory: "512Mi"
