apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-tk831-default-role-nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  target:
    template:
      type: kubernetes.io/basic-auth
    deletionPolicy: Delete
  data:
  - secretKey: username
    remoteRef:
      key: nextcloud
      property: postgres_credentials_username
  - secretKey: password
    remoteRef:
      key: nextcloud
      property: postgres_credentials_password
