apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-tk831-default-role-sparkyfitness-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  target:
    template:
      type: kubernetes.io/basic-auth
    deletionPolicy: Delete
  data:
  - secretKey: username
    remoteRef:
      key: sparky-fitness/postgres-admin/username
  - secretKey: password
    remoteRef:
      key: sparky-fitness/postgres-admin/password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-tk831-default-role-sparkyfitness-app
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  target:
    template:
      type: kubernetes.io/basic-auth
    deletionPolicy: Delete
  data:
  - secretKey: username
    remoteRef:
      key: sparky-fitness/postgres-app/username
  - secretKey: password
    remoteRef:
      key: sparky-fitness/postgres-app/password
