apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kanidm-tls
spec:
  secretName: kanidm-tls
  dnsNames:
  - auth.w7x6t.dev
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
