apiVersion: v1
kind: Service
metadata:
  name: kanidm
  labels:
    app: kanidm
spec:
  type: ClusterIP
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
  - name: ldaps
    protocol: TCP
    port: 636
    targetPort: 3636
  selector:
    app: kanidm
