apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate-mqtt-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: FRIGATE_MQTT_USER
    remoteRef:
      key: frigate/mqtt/username
  - secretKey: FRIGATE_MQTT_PASSWORD
    remoteRef:
      key: frigate/mqtt/password
