apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate-mqtt-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: FRIGATE_MQTT_USER
    remoteRef:
      key: kv/services/frigate/mqtt-credentials
      property: username
  - secretKey: FRIGATE_MQTT_PASSWORD
    remoteRef:
      key: kv/services/frigate/mqtt-credentials
      property: password
