apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate-plus-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: apiKey
    remoteRef:
      key: frigate/frigate-plus/api_key
