apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate-plus-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: apiKey
    remoteRef:
      key: kv/services/frigate/frigate-plus-credentials
      property: api_key
