apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  labels:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: tk831-frigate
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  storageClassName: proxmox-zfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: pvc-5caab176-69c3-4e05-8d95-4f7fd191286e
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
  labels:
    app.kubernetes.io/instance: tk831-frigate
    app.kubernetes.io/name: frigate
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: proxmox-zfs
