apiVersion: v1
kind: Service
metadata:
  name: frigate-webrtc
  labels:
    app.kubernetes.io/name: frigate
spec:
  selector:
    app.kubernetes.io/name: frigate
  ports:
  - name: webrtc
    port: 8555
    protocol: UDP
  type: LoadBalancer
  loadBalancerIP: "172.28.3.135"
