- name: Include distribution specific tasks
  include_tasks: "distribution/{{ ansible_facts['distribution'] | lower }}.yaml"
- name: Get cloudflare_token
  ansible.builtin.set_fact:
    cloudflare_token: "{{(lookup('community.general.onepassword', 'nas-rp-server', vault='Homelab', field='cloudflare_credentials'))}}"
- name: Write Caddyfile
  become: true
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: '0644'
  vars:
    cf_api_token: "{{ cloudflare_token }}"
    hosts: "{{ proxy_hosts }}"
  register: config
- name: Start/Reload caddy
  become: true
  systemd:
    name: caddy
    enabled: true
    state: "{{ 'reloaded' if config.changed else 'started' }}"
