apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden
  labels:
    app.kubernetes.io/name: bitwarden
data:
  SIGNUPS_ALLOWED: 'false'
  WEBSOCKET_ENABLED: 'true'
  DATA_FOLDER: '/data'
  DOMAIN: 'https://bitwarden.tk831.net'
  ROCKET_WORKERS: '10'
  SHOW_PASSWORD_HINT: 'false'
  WEB_VAULT_ENABLED: 'true'
  ROCKET_PORT: '8080'
  HTTP_REQUEST_BLOCK_NON_GLOBAL_IPS: 'false'
  SSO_ENABLED: 'true'
  SSO_ONLY: 'false'
  SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION: 'true'
  SSO_AUTHORITY: https://auth.w7x6t.dev/oauth2/openid/bitwarden
