apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitwarden-oidc-client-credentials
  labels:
    app.kubernetes.io/name: bitwarden
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: clientId
    remoteRef:
      key: kv/services/bitwarden/oauth-client-credentials
      property: client_id
  - secretKey: clientSecret
    remoteRef:
      key: kv/services/bitwarden/oauth-client-credentials
      property: client_secret
