apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-config-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: s3AccessKey
    remoteRef:
      key: kv/services/forgejo/s3-credentials
      property: access_key
  - secretKey: s3SecretKey
    remoteRef:
      key: kv/services/forgejo/s3-credentials
      property: secret_key
  - secretKey: smtpUsername
    remoteRef:
      key: kv/services/forgejo/smtp-credentials
      property: username
  - secretKey: smtpPassword
    remoteRef:
      key: kv/services/forgejo/smtp-credentials
      property: password
  target:
    name: forgejo-config-secret
    template:
      engineVersion: v2
      data:
        storage: |
          STORAGE_TYPE            = minio
          MINIO_ENDPOINT          = s3.tk831.net
          MINIO_BUCKET            = forgejo
          MINIO_LOCATION          = us-east-1
          MINIO_USE_SSL           = true
          MINIO_ACCESS_KEY_ID     = {{ .s3AccessKey }}
          MINIO_SECRET_ACCESS_KEY = {{ .s3SecretKey }}
        mailer: |
          ENABLED   = true
          PROTOCOL  = smtps
          SMTP_ADDR = smtp.tem.scaleway.com
          SMTP_PORT = 465
          FROM      = scm@w7x6t.dev
          USER      = {{ .smtpUsername }}
          PASSWD    = {{ .smtpPassword }}
