apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-config-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: s3_access_key
    remoteRef:
      key: forgejo/s3-credentials/access_key
  - secretKey: s3_secret_key
    remoteRef:
      key: forgejo/s3-credentials/secret_key
  - secretKey: smtp_username
    remoteRef:
      key: forgejo/smtp-credentials/username
  - secretKey: smtp_password
    remoteRef:
      key: forgejo/smtp-credentials/password
  target:
    name: forgejo-config-secret
    template:
      engineVersion: v2
      data:
        storage: |
          STORAGE_TYPE            = minio
          MINIO_ENDPOINT          = s3.tk831.net
          MINIO_BUCKET            = forgejo
          MINIO_LOCATION          = us-east-1
          MINIO_USE_SSL           = true
          MINIO_ACCESS_KEY_ID     = {{ .s3_access_key }}
          MINIO_SECRET_ACCESS_KEY = {{ .s3_secret_key }}
        mailer: |
          ENABLED   = true
          PROTOCOL  = smtps
          SMTP_ADDR = smtp.tem.scaleway.com
          SMTP_PORT = 465
          FROM      = scm@w7x6t.dev
          USER      = {{ .smtp_username }}
          PASSWD    = {{ .smtp_password }}
