apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: op-homelab
spec:
  provider:
    onepassword:
      connectHost: https://op-connect.w7x6t.dev
      vaults:
        Homelab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            namespace: external-secrets
            name: op-homelab-token
            key: token
# onepasswordSDK:
#   vault: Homelab
#   auth:
#     serviceAccountSecretRef:
#       namespace: external-secrets
#       name: op-homelab-token
#       key: token
#   cache:
#     ttl: 12h
#     maxSize: 400
