apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-app-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  target:
    deletionPolicy: Delete
  data:
  - secretKey: NEXTAUTH_SECRET
    remoteRef:
      key: linkwarden/app/cookie_secret
