apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden-app-secrets
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  target:
    deletionPolicy: Delete
  data:
  - secretKey: NEXTAUTH_SECRET
    remoteRef:
      key: kv/services/linkwarden/app-secrets
      property: cookie_secret
