apiVersion: v1
kind: ConfigMap
metadata:
  name: linkwarden
  labels:
    app.kubernetes.io/name: linkwarden
data:
  NEXTAUTH_URL: https://linkwarden.tk831.net/api/v1/auth
  # SSO not functional with kanidm
  # NEXT_PUBLIC_KEYCLOAK_ENABLED: "true"
  KEYCLOAK_CUSTOM_NAME: Kanidm
  KEYCLOAK_ISSUER: https://auth.w7x6t.dev/oauth2/openid/linkwarden
  NEXT_PUBLIC_DISABLE_REGISTRATION: "true"
  NEXT_PUBLIC_CREDENTIALS_ENABLED: "true"
  NEXT_PUBLIC_MAX_FILE_BUFFER: "100"
  PDF_MAX_BUFFER: "300"
  MONOLITH_MAX_BUFFER: "300"
  RSS_SUBSCRIPTION_LIMIT_PER_USER: "100"
  SPACES_ENDPOINT: https://s3.tk831.net
  SPACES_REGION: us-east-1
  SPACES_BUCKET_NAME: linkwarden
  SPACES_FORCE_PATH_STYLE: "true"
