apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-db-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: username
    remoteRef:
      key: linkwarden/postgres/username
  - secretKey: password
    remoteRef:
      key: linkwarden/postgres/password
  target:
    deletionPolicy: Delete
    template:
      type: kubernetes.io/Opaque
      engineVersion: v2
      data:
        DATABASE_URL: |
          postgresql://{{ .username }}:{{ .password }}@postgres-tk831-default-rw.tk831.svc.cluster.local:5432/linkwarden
