apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden-db-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: username
    remoteRef:
      key: kv/services/linkwarden/postgres-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: kv/services/linkwarden/postgres-credentials
      property: password
  target:
    deletionPolicy: Delete
    template:
      type: kubernetes.io/Opaque
      engineVersion: v2
      data:
        DATABASE_URL: |
          postgresql://{{ .username }}:{{ .password }}@postgres-tk831-default-rw.tk831.svc.cluster.local:5432/linkwarden
