apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden-oidc-client-credentials
  labels:
    app.kubernetes.io/name: linkwarden
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: KEYCLOAK_CLIENT_ID
    remoteRef:
      key: kv/services/linkwarden/oauth-client-credentials
      property: client_id
  - secretKey: KEYCLOAK_CLIENT_SECRET
    remoteRef:
      key: kv/services/linkwarden/oauth-client-credentials
      property: client_secret
