apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: linkwarden-http
spec:
  parentRefs:
  - name: default
    namespace: kube-system
    sectionName: http
  hostnames: [linkwarden.tk831.net]
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: linkwarden-https
spec:
  parentRefs:
  - name: default
    namespace: kube-system
    sectionName: https
  hostnames: [linkwarden.tk831.net]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: linkwarden
      port: 80
