apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-s3-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  target:
    deletionPolicy: Delete
  data:
  - secretKey: SPACES_KEY
    remoteRef:
      key: linkwarden
      property: s3_access_key
  - secretKey: SPACES_SECRET
    remoteRef:
      key: linkwarden
      property: s3_secret_key
