apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden-s3-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  target:
    deletionPolicy: Delete
  data:
  - secretKey: SPACES_KEY
    remoteRef:
      key: kv/services/linkwarden/s3-credentials
      property: access_key
  - secretKey: SPACES_SECRET
    remoteRef:
      key: kv/services/linkwarden/s3-credentials
      property: secret_key
