apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: blungebot-service-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  target:
    deletionPolicy: Delete
  data:
  - secretKey: telegram_token
    remoteRef:
      key: blungebot/telegram/token
  - secretKey: mumble_username
    remoteRef:
      key: blungebot/mumble/username
  - secretKey: mumble_password
    remoteRef:
      key: blungebot/mumble/password
