- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: secret-config
    secret:
      secretName: nats-secret-config
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: secret-config
    mountPath: /etc/nats-secret-config
- op: add
  path: /spec/template/spec/containers/1/volumeMounts/-
  value:
    name: secret-config
    mountPath: /etc/nats-secret-config
