apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
spec:
  secretStoreRef:
    name: op-homelab
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: api_token
    remoteRef:
      key: cert-manager
      property: cloudflare_api_token
