- name: Ensure Victoria Metrics directories exist
  become: true
  loop:
  - /var/mnt/victoriametrics/data
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: victoria-metrics
    group: victoria-metrics
    mode: '0750'
- name: Create Victoria Metrics quadlet
  become: true
  containers.podman.podman_container:
    name: victoria-metrics
    state: quadlet
    image: docker.io/victoriametrics/victoria-metrics:v1.132.0
    uidmap: ["0:2003"]
    command:
    - -storageDataPath=/mnt/data
    - -retentionPeriod=4w
    volume:
    - /var/mnt/victoriametrics/data:/mnt/data:Z
    network:
    - podman
    - observability-stack.network
    ports:
    - "8428:8428"
    quadlet_options:
    - |
      [Unit]
      RequiresMountsFor=/var/mnt/victoriametrics/data

      [Service]
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=default.target
  register: container_definition
- name: systemd daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
- name: (Re)start victoria-metrics service
  become: true
  ansible.builtin.systemd:
    name: victoria-metrics
    enabled: true
    state: "{{ 'restarted' if container_definition.changed else 'started' }}"
