apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blunge-app-of-apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: blunge
  source:
    repoURL: https://scm.w7x6t.dev/wtaylor/homelab.git
    path: ./kubernetes/by-cluster/red-squadron-talos/blunge/app-of-apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
