- hosts: rootn.willtaylor.info
  remote_user: ansible
  pre_tasks:
  - name: Mount ROOTS
    local_action: ansible.builtin.shell
    args:
      chdir: "{{ playbook_dir }}"
      cmd: "../../../scripts/mount_roots.sh"
    changed_when: false
  post_tasks:
  - name: Unmount ROOTS
    local_action: ansible.builtin.shell
    args:
      chdir: "{{ playbook_dir }}"
      cmd: "../../../scripts/unmount_roots.sh"
    changed_when: false
  roles:
  - role: ../../../common/roles/create-system-users
    system_users:
    - username: openbao
      uid: 2000
  - role: ../../../common/roles/mount-encrypted-disk
    backing_device_uuid: 8658de3c-d4aa-4b64-9b73-42083316d611
    decrypted_fs_uuid: 9a7d845b-ae34-4e2d-b84d-2c90a3973288
    disk_mapper_name: rootn
    keyfile:
      src: /run/media/wtaylor/ROOTS/keys/rootn-keyfile
      dest: /root/rootn-keyfile
      owner: root
      group: root
      mode: '0600'
    mountpoint:
      path: /mnt/rootn
      owner: root
      group: root
      mode: '0755'
  - role: ../../../common/roles/certificates
    cloudflare_token: "{{ lookup('ansible.builtin.file', '/run/media/wtaylor/ROOTS/secrets/cloudflare_token') }}"
    domains:
    - vault.rootn.tk831.net
    contact_mail: me@willtaylor.info
    deploy_hook: |
      #!/bin/sh

      CERT_DIR="/mnt/rootn/certs"

      cat $RENEWED_LINEAGE/cert.pem > $CERT_DIR/cert.pem
      cat $RENEWED_LINEAGE/fullchain.pem > $CERT_DIR/fullchain.pem
      cat $RENEWED_LINEAGE/privkey.pem > $CERT_DIR/privkey.pem

      chown openbao:openbao $CERT_DIR/cert.pem
      chown openbao:openbao $CERT_DIR/fullchain.pem
      chown openbao:openbao $CERT_DIR/privkey.pem

      systemctl restart openbao.service
  - role: ./roles/configure-openbao
  - role: ../../../common/roles/restic-backup
    repository:
      url: rest:http://data-backup-server.willtaylor.info:8080/hosts/rootn
      password: "{{ lookup('ansible.builtin.file', '/run/media/wtaylor/ROOTS/secrets/restic_repo_password') }}"
      rest_username: "{{ lookup('ansible.builtin.file', '/run/media/wtaylor/ROOTS/secrets/restic_rest_username') }}"
      rest_password: "{{ lookup('ansible.builtin.file', '/run/media/wtaylor/ROOTS/secrets/restic_rest_password') }}"
    retention:
      daily: 7
      weekly: 4
      monthly: 3
      yearly: 2
    systemd:
      on_calendar: "*-*-* 02:00:00"
      unit_suffix: host
    backup_now: false
    directories:
    - /mnt/rootn/openbao
    - /mnt/rootn/certs
  - role: ../../../common/roles/vector-agent
    tags: [vector-agent]
    install: true
    agent_user:
      groups: [systemd-journal]
    vector_config:
      data_dir: /opt/vector/data
      api:
        enabled: true
      schema:
        log_namespace: true
      sources:
        vector_logs:
          type: internal_logs
        journald:
          type: journald
        host_metrics:
          type: host_metrics
          scrape_interval_secs: 60
          filesystem:
            devices:
              excludes: [binfmt_misc]
            filesystems:
              includes:
              - ext*
              - xfs
              - ntfs
              - btrfs
              - zfs
              - vfat
              - fat32
            mountPoints:
              excludes:
              - "*/proc/sys/fs/binfmt_misc"
              - "/var/lib/containers/**"
        vector_internal_metrics:
          type: internal_metrics
          scrape_interval_secs: 60
      transforms:
        mapped_journal_logs:
          type: remap
          inputs: [journald]
          source: |-
            .message = .
            .timestamp = %journald.timestamp
            .host = %journald.host
            .service = %journald.metadata._SYSTEMD_UNIT
      sinks:
        console:
          type: console
          inputs: ["vector_logs"]
          encoding:
            codec: text
        vector_server:
          type: vector
          inputs: [host_metrics, mapped_journal_logs, vector_internal_metrics]
          address: http://vector.tk831.net:6001
          version: "2"
          tls:
            enabled: false
