apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/deployment.yaml
- resources/service.yaml
- resources/storage.yaml
- resources/routes.yaml
- resources/secret-frigate-plus.yaml
- resources/secret-mqtt.yaml
- resources/webrtc-loadbalancer.yaml
