apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.tk831.net
  oidc.config: |
    name: Kanidm
    issuer: https://auth.w7x6t.dev/oauth2/openid/argocd
    clientID: argocd
    enablePKCEAuthentication: true
    clientSecret: $oidc.client.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups_name"]
  kustomize.buildOptions: --enable-helm
