apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparky-fitness-app-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: api_encryption_key
    remoteRef:
      key: sparky-fitness
      property: app_api_encryption_key
  - secretKey: better_auth_secret
    remoteRef:
      key: sparky-fitness
      property: app_better_auth_secret
