apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sparky-fitness-app-secrets
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: api_encryption_key
    remoteRef:
      key: kv/services/sparky-fitness/app-secrets
      property: api_encryption_key
  - secretKey: better_auth_secret
    remoteRef:
      key: kv/services/sparky-fitness/app-secrets
      property: better_auth_secret
