apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sparky-fitness-oauth-client-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: client_id
    remoteRef:
      key: kv/services/sparky-fitness/oauth-client-credentials
      property: client_id
  - secretKey: client_secret
    remoteRef:
      key: kv/services/sparky-fitness/oauth-client-credentials
      property: client_secret
