apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sparky-fitness-postgres-credentials
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 5m
  data:
  - secretKey: username
    remoteRef:
      key: kv/services/sparky-fitness/postgres-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: kv/services/sparky-fitness/postgres-credentials
      property: password
