apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparky-fitness-postgres-app-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-homelab
  refreshInterval: 5m
  data:
  - secretKey: username
    remoteRef:
      key: sparky-fitness
      property: postgres_app_username
  - secretKey: password
    remoteRef:
      key: sparky-fitness
      property: postgres_app_password
